# Tech News Site - Daily Update Script
# This script fetches news using Claude Code and updates the website
#
# Usage:
#   .\update-news.ps1              # Fetch news and update site
#   .\update-news.ps1 -Deploy      # Also push to GitHub

param(
    [switch]$Deploy = $false,
    [string]$SiteDir = "$env:USERPROFILE\Projects\tech-news-site"
)

$ErrorActionPreference = "Stop"
$Date = Get-Date -Format "yyyy-MM-dd"
$DocsDir = Join-Path $SiteDir "docs"
$NewsDataFile = Join-Path $DocsDir "assets\js\news-data.js"
$FeedFile = Join-Path $DocsDir "feed.xml"

Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Tech Daily - News Update Script" -ForegroundColor Cyan
Write-Host " Date: $Date" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Step 1: Fetch news using Claude Code
Write-Host "[1/4] Fetching latest news..." -ForegroundColor Yellow

$prompt = @"
请获取今天（$Date）的科技新闻，覆盖以下领域：
1. 人工智能 (AI)
2. 汽车/新能源
3. AI硬件与嵌入式
4. 汽车电子嵌入式
5. 消费电子
6. 集成电路/半导体

请输出为 JSON 格式，结构如下：
{
    "date": "$Date",
    "highlights": [
        {"title": "标题", "summary": "摘要", "source": "来源", "url": "链接", "category": "ai/auto/chip/embedded/consumer"}
    ],
    "categories": {
        "ai": {"name": "人工智能", "icon": "&#129302;", "items": [...]},
        ...
    }
}

只输出 JSON，不要其他内容。
"@

# Create a temporary file to store the prompt
$TempPromptFile = Join-Path $env:TEMP "news_prompt_$Date.txt"
$prompt | Out-File -FilePath $TempPromptFile -Encoding UTF8

try {
    $newsJson = claude -p $prompt 2>&1

    if ($LASTEXITCODE -ne 0) {
        Write-Host "Error fetching news: $newsJson" -ForegroundColor Red
        exit 1
    }

    Write-Host "News fetched successfully!" -ForegroundColor Green
}
catch {
    Write-Host "Error: $_" -ForegroundColor Red
    exit 1
}

# Step 2: Update news-data.js
Write-Host ""
Write-Host "[2/4] Updating news data file..." -ForegroundColor Yellow

# Extract JSON from response (handle potential markdown code blocks)
$jsonContent = $newsJson -replace '```json', '' -replace '```', '' | Out-String

# Create the JavaScript file content
$jsContent = @"
// News Data - Auto-generated by Tech News Researcher
// Last updated: $Date
const NEWS_DATA = $jsonContent;

// Email subscribers storage key
const SUBSCRIBERS_KEY = 'tech_daily_subscribers';
"@

try {
    $jsContent | Out-File -FilePath $NewsDataFile -Encoding UTF8
    Write-Host "Updated: $NewsDataFile" -ForegroundColor Green
}
catch {
    Write-Host "Error updating news data: $_" -ForegroundColor Red
}

# Step 3: Update RSS feed
Write-Host ""
Write-Host "[3/4] Updating RSS feed..." -ForegroundColor Yellow

# Parse the JSON to generate RSS items
# (In a production script, you'd parse the JSON properly)
Write-Host "RSS feed update requires manual review" -ForegroundColor Yellow

# Step 4: Deploy to GitHub (optional)
if ($Deploy) {
    Write-Host ""
    Write-Host "[4/4] Deploying to GitHub..." -ForegroundColor Yellow

    Push-Location $SiteDir
    try {
        git add -A
        git commit -m "Daily news update: $Date"
        git push origin main
        Write-Host "Deployed successfully!" -ForegroundColor Green
    }
    catch {
        Write-Host "Error deploying: $_" -ForegroundColor Red
    }
    finally {
        Pop-Location
    }
}
else {
    Write-Host ""
    Write-Host "[4/4] Skipping deployment (use -Deploy flag to enable)" -ForegroundColor Gray
}

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host " Update Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "To preview locally:"
Write-Host "  cd $DocsDir && python -m http.server 8080"
Write-Host ""
Write-Host "To deploy to GitHub:"
Write-Host "  .\update-news.ps1 -Deploy"
Write-Host ""

<#
=== Setup Windows Scheduled Task ===

Run as Administrator:

$Action = New-ScheduledTaskAction -Execute "powershell.exe" `
    -Argument "-ExecutionPolicy Bypass -File `"$env:USERPROFILE\Projects\tech-news-site\scripts\update-news.ps1`" -Deploy"
$Trigger = New-ScheduledTaskTrigger -Daily -At "07:30"
$Settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable

Register-ScheduledTask -TaskName "TechDailyUpdate" -Action $Action -Trigger $Trigger -Settings $Settings `
    -Description "Update Tech Daily news site"

# Manual run
Start-ScheduledTask -TaskName "TechDailyUpdate"

# Remove task
Unregister-ScheduledTask -TaskName "TechDailyUpdate" -Confirm:$false

#>
